---
- name: Installer ufw
  ansible.builtin.apt:
    name: ufw
    state: present
  become: true

- name: Autoriser SSH
  community.general.ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp
  become: true
  when: not ansible_check_mode

- name: Autoriser node_exporter depuis le VCN
  community.general.ufw:
    rule: allow
    port: "9100"
    proto: tcp
    from_ip: "10.0.0.0/16"
  become: true
  when: not ansible_check_mode

- name: Définir la politique entrante par défaut
  community.general.ufw:
    direction: incoming
    policy: deny
  become: true
  when: not ansible_check_mode

- name: Définir la politique sortante par défaut
  community.general.ufw:
    direction: outgoing
    policy: allow
  become: true
  when: not ansible_check_mode

- name: Autoriser node_exporter dans iptables
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "9100"
    jump: ACCEPT
    action: insert
    rule_num: 1
  become: true
  when: not ansible_check_mode

- name: Activer ufw
  community.general.ufw:
    state: enabled
  become: true
  when: not ansible_check_mode
