---
- name: Configuration commune des serveurs Linux
  hosts: linux
  become: true
  roles:
    - common
    - ssh_hardening
    - fail2ban
    - firewall
    - node_exporter

- name: Installation de Prometheus et Grafana sur le bastion
  hosts: bastion
  become: true
  roles:
    - prometheus
    - grafana
